name: tilde_expansion
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/nohkumado/dart_tilde_expansion/

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
   path: ^1.9.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.8
